Repository CRPropa/CRPropa3, pull requests merged in 2024-02, with the labels that each got.

#468 fix upper limit of tabulated data in ICSSecondariesEnergyDistribution
  doc/pages/example_notebooks/secondaries/photons.ipynb
  src/module/EMInverseComptonScattering.cpp
Labels: bug

#466 Fix problems with Python, improve installation, and improve tests
  .github/workflows/test_examples.yml
  .github/workflows/testing_OSX.yml
  .github/workflows/testing_ubuntu20.yml
  .github/workflows/testing_ubuntu22.yml
  CMakeLists.txt
  cmake/FindSAGA.cmake
  cmake/FindSQLite3.cmake
  python/1_swig.i
  python/2_headers.i
  python/3_repr.i
  python/4_lens.i
  python/Python.cmake
  python/checkMatplotlib.py
  python/checkNumpy.py
  python/crpropa-builtin.i
  src/module/EMPairProduction.cpp
  test/testCore.cpp
  test/testInteraction.cpp
  test/testOutput.cpp
  test/testPropagation.cpp
  test/testPythonExtension.py
  test/testTurbulentField.cpp
Labels: bug, enhancement, installation

#471 updated doc for new Python interface via cmake
  doc/pages/Installation.md
Labels: documentation
